plugins {
    id 'com.android.application' version '9.3.0' apply false
    id 'com.android.library' version '9.3.0' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.getProjectDir().absolutePath + "/app/debug"
    delete rootProject.getProjectDir().absolutePath + "/app/release"
}